# =============================================================================
# 课程管理路由
# 课程 CRUD、课程生成、节点级操作、大纲编辑、生成配置
# =============================================================================

from fastapi import APIRouter, Depends, HTTPException
from fastapi.concurrency import run_in_threadpool
from pydantic import BaseModel
from typing import Optional, List
import sys
import os

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from models import GenerateCourseRequest, LocateNodeRequest, NodeGenerationConfig
from storage import storage
from ai_service import ai_service
from dependencies import get_course_or_404, require_task_manager, get_node_or_404
from task_manager import TaskManager

router = APIRouter(tags=["courses"])


# =============================================================================
# Request models for new endpoints
# =============================================================================

class CustomInstructionRequest(BaseModel):
    """Request body for setting a custom instruction on a node."""
    instruction: str


class OutlineUpdateRequest(BaseModel):
    """Request body for updating course outline."""
    nodes: List[dict]


class NodeConfigUpdateRequest(BaseModel):
    """Request body for updating a node's generation config."""
    difficulty: Optional[str] = None
    style: Optional[str] = None
    target_word_range: Optional[tuple] = None
    include_code_examples: Optional[bool] = None
    include_exercises: Optional[bool] = None
    custom_instruction: Optional[str] = None


# =============================================================================
# Existing endpoints (backward compatible)
# =============================================================================


@router.get("/courses")
async def list_courses():
    return await run_in_threadpool(storage.list_courses)


@router.get("/courses/{course_id}")
async def get_course(course_id: str):
    return await get_course_or_404(course_id)


@router.delete("/courses/{course_id}")
async def delete_course(course_id: str):
    await run_in_threadpool(storage.delete_course, course_id)
    return {"status": "success"}


@router.post("/generate_course")
async def generate_course(req: GenerateCourseRequest):
    # Map frontend difficulty/style to CourseService parameters
    depth_mapping = {
        "beginner": "入门",
        "intermediate": "中级",
        "advanced": "高级",
    }
    depth = depth_mapping.get(req.difficulty, "中级") if req.difficulty else "中级"

    data = await ai_service.generate_course(
        topic=req.keyword,
        target_audience="大学生",
        depth=depth,
    )

    # Use the course_id generated by CourseService (keeps internal state consistent)
    course_id = data["course_id"]

    # Attach frontend-facing metadata
    data["difficulty"] = req.difficulty or "intermediate"
    data["style"] = req.style or "academic"
    data["requirements"] = req.requirements or ""

    await storage.save_course(course_id, data)
    return data


@router.post("/courses/{course_id}/locate")
async def locate_node(course_id: str, req: LocateNodeRequest):
    tree_data = await get_course_or_404(course_id)
    if "nodes" not in tree_data:
        return {}
    return await ai_service.locate_node(req.keyword, tree_data["nodes"])


# =============================================================================
# Node-level operations (HTTP fallback for WebSocket commands)
# Requirements: 7.1, 7.2, 7.3, 7.4
# =============================================================================


@router.post("/courses/{course_id}/nodes/{node_id}/skip")
async def skip_node(
    course_id: str,
    node_id: str,
    tm: TaskManager = Depends(require_task_manager),
):
    """Skip a node during generation."""
    task_id = tm._find_active_task(course_id)
    if not task_id:
        raise HTTPException(status_code=404, detail="No active task for this course")
    await tm.skip_node(task_id, node_id)
    return {"status": "skipped"}


@router.post("/courses/{course_id}/nodes/{node_id}/retry")
async def retry_node(
    course_id: str,
    node_id: str,
    tm: TaskManager = Depends(require_task_manager),
):
    """Retry a failed or completed node."""
    task_id = tm._find_active_task(course_id)
    if not task_id:
        raise HTTPException(status_code=404, detail="No active task for this course")
    await tm.retry_node(task_id, node_id)
    return {"status": "retry_scheduled"}


@router.post("/courses/{course_id}/nodes/{node_id}/stop")
async def stop_node(
    course_id: str,
    node_id: str,
    tm: TaskManager = Depends(require_task_manager),
):
    """Stop generating a node, keeping already-generated content."""
    task_id = tm._find_active_task(course_id)
    if not task_id:
        raise HTTPException(status_code=404, detail="No active task for this course")
    await tm.stop_node(task_id, node_id)
    return {"status": "stopped"}


@router.post("/courses/{course_id}/nodes/{node_id}/instruction")
async def set_custom_instruction(
    course_id: str,
    node_id: str,
    body: CustomInstructionRequest,
    tm: TaskManager = Depends(require_task_manager),
):
    """Set a custom generation instruction for a node."""
    await tm._set_custom_instruction(course_id, node_id, body.instruction)
    return {"status": "instruction_set"}


@router.post("/courses/{course_id}/retry_all_failed")
async def retry_all_failed(
    course_id: str,
    tm: TaskManager = Depends(require_task_manager),
):
    """Retry all failed nodes for a course."""
    task_id = tm._find_active_task(course_id)
    if not task_id:
        raise HTTPException(status_code=404, detail="No active task for this course")
    await tm.retry_all_failed(task_id)
    return {"status": "retry_all_scheduled"}


# =============================================================================
# Outline editing
# Requirements: 6.3
# =============================================================================


@router.put("/courses/{course_id}/outline")
async def update_outline(
    course_id: str,
    body: OutlineUpdateRequest,
    tm: TaskManager = Depends(require_task_manager),
):
    """Update course outline and reschedule generation."""
    task_id = tm._find_active_task(course_id)
    if not task_id:
        raise HTTPException(status_code=404, detail="No active task for this course")
    await tm.update_outline(task_id, body.nodes)
    return {"status": "outline_updated"}


# =============================================================================
# Generation config
# Requirements: 14.4
# =============================================================================


@router.put("/courses/{course_id}/nodes/{node_id}/config")
async def update_node_config(
    course_id: str,
    node_id: str,
    body: NodeConfigUpdateRequest,
):
    """Update generation config for a specific node."""
    tree_data = await get_course_or_404(course_id)
    node = get_node_or_404(tree_data, node_id)

    config = node.get("generation_config") or {}
    update_data = body.model_dump(exclude_none=True)
    config.update(update_data)
    node["generation_config"] = config

    await storage.save_course(course_id, tree_data)
    return {"status": "config_updated", "config": config}
