import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const sourceRoot = resolve(process.cwd(), 'src')
const source = (path: string) => readFileSync(resolve(sourceRoot, path), 'utf8')

describe('calendar and course file-space boundary', () => {
  it('uses the calendar as home and removes the duplicated global stage bar', () => {
    const workspace = source('views/CourseWorkspaceView.vue')
    const app = source('App.vue')
    const home = source('views/TeacherTeachingCalendarView.vue')

    expect(app).not.toContain('CourseStageTabs')
    expect(app).not.toContain('class="app-course-stages"')
    expect(home).toContain('class="course-rail"')
    expect(home).toContain('class="course-search" role="search"')
    expect(home).toContain("t('teacherHome.noSearchResults')")
    expect(home).toContain("@click=\"courseQuery = ''\"")
    expect(home).toContain('class="calendar-surface"')
    expect(home).toContain('class="day-inspector"')
    expect(home).toContain('<CreateCourseSpaceDialog')
    expect(home).not.toContain('<CourseGenerationDialog')
    expect(home).not.toContain('v-if="!visibleSessions.length" class="calendar-empty"')
    expect(workspace).toContain('<TeacherCourseSpaceView')
    expect(workspace).toContain('<CourseOutlineReview')
    expect(workspace.match(/<GenerationLessonPlan[\s\S]*?embedded/g)).toHaveLength(1)
    expect(workspace).toContain('<Teleport to="#app-header-route-actions">')
    expect(workspace).toContain('mode="teacher"')
    expect(workspace).toContain('@click="openCoursePreview"')
    expect(workspace).not.toContain('workspace-subtabs')
    expect(workspace).not.toContain('<TeacherCourseCalendarView')
    expect(workspace).not.toContain('useTeacherCourseRuntime')
  })

  it('keeps active routes in one namespace and redirects legacy teacher URLs', () => {
    const router = source('router/index.ts')

    expect(router).toContain("path: '/courses'")
    expect(router).toContain("path: '/course/:courseId/workspace/:mode(setup|build)?'")
    expect(router).toContain("path: '/course/:courseId/learn/:nodeId?'")
    expect(router).toContain("path: '/course/:courseId/ppt'")
    expect(router).toContain("component: () => import('../views/TeacherTeachingCalendarView.vue')")
    expect(router).toMatch(/path:\s*'\/teacher\/course\/:courseId\/files'[\s\S]*?redirect:[\s\S]*?name:\s*'course-workspace'/)
    expect(router).toMatch(/path:\s*'\/teacher\/course\/:courseId\/teaching-calendar'[\s\S]*?redirect:[\s\S]*?name:\s*'course-library'/)
    expect(router).toMatch(/path:\s*'\/teacher\/:pathMatch\(\.\*\)\*'[\s\S]*?redirect:\s*'\/courses'/)
    expect(router).not.toContain("import('../views/TeacherCourseOverviewView.vue')")
    expect(router).not.toContain("import('../views/TeacherCourseProductionView.vue')")
  })

  it('opens managed outline and lesson-plan files in drawers without adding tabs', () => {
    const workspace = source('views/CourseWorkspaceView.vue')
    const lessonPlan = source('components/GenerationLessonPlan.vue')

    expect(workspace.match(/<GenerationLessonPlan/g)).toHaveLength(1)
    expect(workspace).toContain(':plan="selectedLessonPlan"')
    expect(workspace).toContain('@open-outline="outlineOpen = true"')
    expect(workspace).toContain('@create-outline="generationDialogOpen = true"')
    expect(workspace).toContain("target_course_id: courseId.value")
    expect(workspace).toContain('@open-teaching-plan="openLessonPlan"')
    expect(lessonPlan).toContain("visibleScope?: 'both' | 'overall' | 'sections'")
    expect(lessonPlan).toContain('embedded?: boolean')
    expect(lessonPlan).toContain('v-if="!embedded" class="generation-lesson-plan__intro"')
    expect(lessonPlan).not.toContain('teacherLessonAuthoring')
  })

  it('binds the file space to the stable course and presents one managed file tree', () => {
    const fileSpace = source('views/TeacherCourseSpaceView.vue')

    expect(fileSpace).toContain("params: embedded.value && props.courseId ? { course_id: props.courseId } : undefined")
    expect(fileSpace).toContain("course_id: props.courseId")
    expect(fileSpace).toContain("http.patch(`/api/teacher-course-spaces/${legacyMatches[0]!.package_id}`")
    expect(fileSpace).toContain('class="file-tree-pane"')
    expect(fileSpace).toContain('class="folder-navigation"')
    expect(fileSpace).toContain('<WorkspaceFolderTreeNode')
    expect(fileSpace).not.toContain('<el-tree')
    expect(fileSpace).toContain('class="file-list-pane"')
    expect(fileSpace).toContain('class="file-inspector"')
    expect(fileSpace).toContain("t('courseFiles.columns.size')")
    expect(fileSpace).toContain('const inspectedNode = computed')
    expect(fileSpace).toContain("id: `content:${lesson.lesson_unit_id}`")
    expect(fileSpace).toContain('async function exportManagedNode')
    expect(fileSpace).toContain("node.type === 'content'")
    expect(fileSpace).toContain("type CreateType = 'outline' | 'lesson_plan' | 'material' | 'ppt' | 'practice' | 'folder'")
    expect(fileSpace).not.toContain('class="new-button"')
    expect(fileSpace).not.toContain('<el-dropdown')
    expect(fileSpace).toContain('const canAddTeacherFiles = computed')
    expect(fileSpace).toContain("t('courseFiles.addMaterial')")
    expect(fileSpace).toContain(':data-role="assetRole(node)"')
    expect(fileSpace).toContain('function handleNodeClick(node: WorkspaceNode)')
    expect(fileSpace).toContain('function selectNode(node: WorkspaceNode)')
    expect(fileSpace).toContain("@dblclick=\"node.kind !== 'folder' && primaryAction(node)\"")
    expect(fileSpace).toContain('@click="handleNodeClick(node)"')
    expect(fileSpace).toContain("id: `ppt:${lesson.lesson_unit_id}`")
    expect(fileSpace).not.toContain('ppt || !uploadedPpts.length')
  })

  it('keeps practice out of the top workspace and routes it through the student question book', () => {
    const learning = source('views/LearningView.vue')
    const dock = source('components/LearningDock.vue')

    expect(learning).toContain(':show-lesson-plan="isGenerationPreview"')
    expect(learning).toContain('@question-book="openQuestionBook"')
    expect(learning).not.toContain("workspace === 'practice'")
    expect(dock).toContain('data-domain="question-book"')
  })

  it('does not repeat controls with explanatory copy on the active teacher path', () => {
    const home = source('views/TeacherTeachingCalendarView.vue')
    const courseDialog = source('components/CreateCourseSpaceDialog.vue')
    const fileSpace = source('views/TeacherCourseSpaceView.vue')
    const generationDialog = source('components/CourseGenerationDialog.vue')
    const taskCenter = source('components/CourseTaskCenter.vue')
    const questionBank = source('components/QuestionBankReviewPanel.vue')

    expect(home).not.toContain("t('teacherHome.noSearchResultsHelp')")
    expect(courseDialog).not.toContain("t('courseSpaceCreate.rule')")
    expect(fileSpace).not.toContain('<p class="asset-create-help"')
    expect(fileSpace).not.toContain('emptyFolderHelp')
    expect(fileSpace).not.toContain('sourceHint')
    expect(fileSpace).not.toContain('<p v-if="createType === \'ppt\'" class="ppt-origin-note"')
    expect(generationDialog).not.toContain('<p class="starting-point-note"')
    expect(generationDialog).not.toContain('<p class="difficulty-summary"')
    expect(taskCenter).not.toContain('currentReviewHelp')
    expect(questionBank).not.toContain("t('questionBank.noMatchingQuestionsHelp'")
  })
})
