import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const sourceRoot = resolve(process.cwd(), 'src')
const source = (path: string) => readFileSync(resolve(sourceRoot, path), 'utf8')

describe('calendar and course file-space boundary', () => {
  it('keeps both primary home tabs and makes the calendar rail an explicit course filter', () => {
    const workspace = source('views/CourseWorkspaceView.vue')
    const workbench = source('components/TeacherCourseWorkbench.vue')
    const app = source('App.vue')
    const home = source('views/TeacherTeachingCalendarView.vue')

    expect(app).not.toContain('CourseStageTabs')
    expect(app).not.toContain('class="app-course-stages"')
    expect(home).toContain('class="home-primary-tabs"')
    expect(home).toContain("activeHomeTab === 'calendar'")
    expect(home).toContain("activeHomeTab === 'courses'")
    expect(home).toContain('<TeacherCourseLibraryView')
    expect(home).toContain('embedded />')
    expect(home).toContain('class="course-rail"')
    expect(home).not.toContain('class="course-search" role="search"')
    expect(home).toContain('class="course-list" role="group"')
    expect(home).toContain('class="course-filter-reset"')
    expect(home).toContain(':aria-pressed="selectedCourseId === course.course_id"')
    expect(home).toContain('class="course-icon"')
    expect(home).not.toContain('class="course-filter-all"')
    expect(home).not.toContain('class="course-filter-marker"')
    expect(home).not.toContain('class="course-entry__count"')
    expect(home).toContain("t('teacherHome.courseFilterTitle')")
    expect(home).toContain("t('teacherHome.courseFilterSelectedHint')")
    expect(home).toContain("t('teacherHome.courseFilterEmpty')")
    expect(home).toContain('class="calendar-filter-status" role="status"')
    expect(home).not.toContain('class="calendar-filter-empty"')
    expect(home).toContain('.course-entry{margin-bottom:2px;border:1px solid transparent}')
    expect(home).toContain('.course-entry.active{color:var(--lz-brand-strong);border-color:color-mix(in srgb,var(--lz-brand) 18%,transparent);background:var(--lz-brand-soft);box-shadow:none}')
    expect(home).toContain('.course-entry.active .course-icon{color:var(--lz-brand-strong);background:transparent}')
    expect(home).toContain('v-for="(course, index) in recentCourses"')
    expect(home).toContain('@click="focusCourse(course)"')
    expect(home).toContain("t('teacherHome.enterCourseNamed')")
    expect(home).toContain("switchHomeTab('courses')")
    expect(home).toContain('courseStore.courseList')
    expect(home).toContain("availableCourseIds.value.has(String(item.course_id || ''))")
    expect(home).not.toContain('candidates.set(session.course_id')
    expect(home).toContain('.slice(0, 6)')
    expect(home).not.toContain('<TeacherCourseCalendarView')
    expect(home).toContain('class="calendar-surface"')
    expect(home).toContain('.week-canvas{grid-row:3;min-width:0;min-height:0;overflow:auto;padding:0;background:#fff;')
    expect(home).toContain('.week-canvas::-webkit-scrollbar{width:8px;height:8px}')
    expect(home).toContain('.week-canvas::-webkit-scrollbar-thumb{min-height:56px;border:2px solid transparent;border-radius:999px;background:color-mix(in srgb,var(--lz-brand) 24%,var(--lz-border));background-clip:padding-box}')
    expect(home).toContain('min-width:980px;min-height:100%;display:grid;')
    expect(home).toContain('overflow:clip;border:0;border-radius:0;background:#fff;box-shadow:none;')
    expect(home).toContain('class="day-inspector"')
    expect(home).toContain(':selected-date="selectedDate"')
    expect(home).toContain('@day="selectDay"')
    expect(home).toContain("create: 'course'")
    expect(home).toContain('<TeacherCourseCreateView v-if="courseCreateOpen"')
    expect(home).not.toContain('<CreateCourseSpaceDialog')
    expect(home).not.toContain('<CourseGenerationDialog')
    expect(home).not.toContain('v-if="!visibleSessions.length" class="calendar-empty"')
    const focusCourse = home.match(/function focusCourse\(course: Course\) \{[\s\S]*?\n\}/)?.[0] || ''
    expect(focusCourse).toContain('selectedCourseId.value = course.course_id')
    expect(focusCourse).not.toContain('cursor.value')
    expect(focusCourse).not.toContain('clearCourseFilter()')
    expect(workspace).toContain('<TeacherCourseSpaceView')
    expect(workspace).not.toContain('<CourseOutlineReview')
    expect(workbench).toContain('<CourseOutlineReview')
    expect(workspace).not.toContain('<GenerationLessonPlan')
    expect(workbench).toContain('<TeacherLessonPlanDocument')
    expect(workspace).toContain('<Teleport to="#app-header-route-actions">')
    expect(workspace).toContain('<Teleport to="#app-header-route-context">')
    expect(workspace).toContain('<Teleport to="#app-header-route-center">')
    expect(app).toContain('id="app-header-route-context"')
    expect(app).toContain('id="app-header-route-center"')
    expect(workspace).toContain('class="workspace-search workspace-search--inline"')
    expect(workspace).toContain('v-model:query="searchQuery"')
    expect(workspace).not.toContain('class="task-action"')
    expect(workspace).toContain('class="preview-action"')
    expect(workspace).not.toContain('class="workspace-local-header"')
    expect(workspace).toContain('<TeacherCourseWorkbench')
    expect(workspace).toContain("loadError.status === 404 ? backToSource() : loadWorkspace()")
    expect(workspace).not.toContain("teacherRequestConfig({ silentError: true }),\n    ).catch(() => ({ data: {} }))")
    expect(workspace).not.toContain('<SideAIPanel')
    expect(workspace).toContain('workspace-view="files"')
    expect(workspace).toContain('class="workspace-operating-shell"')
    expect(workspace).toContain('@click="openCoursePreview"')
    expect(workspace).not.toContain('workspace-subtabs')
    expect(workspace).toContain('<TeacherCourseCalendarView embedded />')
    expect(workspace).not.toContain('useTeacherCourseRuntime')
  })

  it('turns the selected calendar session into a compact preparation decision panel', () => {
    const home = source('views/TeacherTeachingCalendarView.vue')
    const workspace = source('views/CourseWorkspaceView.vue')
    const workbench = source('components/TeacherCourseWorkbench.vue')

    expect(home).toContain('class="session-inspector-body"')
    expect(home).toContain("t('teacherHome.sessionPanel.teacher')")
    expect(home).toContain('selectedSession.teacher_name')
    expect(home).toContain('outlinePreparation.detail')
    expect(home).toContain('lessonPlanPreparation.detail')
    expect(home).toContain('pptPreparation.detail')
    expect(home).toContain("/lesson-authoring`")
    expect(home).toContain('preparationPrimaryLabel')
    expect(home).toContain("stage: preparationNextStage.value")
    expect(workspace).toContain(':initial-lesson-id="requestedLessonId"')
    expect(workspace).toContain('route.query.stage')
    expect(workbench).toContain('initialLessonId?: string')
  })

  it('keeps dense course cards and gives list mode a compact aligned comparison surface', () => {
    const library = source('views/TeacherCourseLibraryView.vue')

    expect(library).toContain("grid-template-columns:repeat(3,minmax(0,1fr))")
    expect(library).toContain("'course-collection--list': displayMode === 'list'")
    expect(library).toContain('class="course-list-columns"')
    expect(library).toContain('--course-list-main-columns:')
    expect(library).toContain(".course-grid[data-view='list'] .course-main")
    expect(library).toContain("max-width:none")
    expect(library).toContain("grid-template-areas:'identity status time location term version'")
    expect(library).toContain(".course-grid[data-view='list'] .course-field--muted strong")
    expect(library).toContain('min-height:66px')
    expect(library).not.toContain('.course-grid:has(.course-item:only-child)')
  })

  it('opens both teaching calendars on the Zhejiang University weekly timetable', () => {
    const home = source('views/TeacherTeachingCalendarView.vue')
    const courseCalendar = source('views/TeacherCourseCalendarView.vue')

    expect(home).toContain("const view = ref<'month' | 'week'>('week')")
    expect(courseCalendar).toContain("const view = ref<'table' | 'month' | 'week'>('week')")
    expect(home.indexOf("view === 'week'")).toBeLessThan(home.indexOf("view === 'month'"))
    expect(courseCalendar.indexOf('data-testid="calendar-week-view"')).toBeLessThan(courseCalendar.indexOf('data-testid="calendar-month-view"'))
    expect(home).toContain('class="total-week-grid"')
    expect(courseCalendar).toContain('class="course-week-grid"')
    expect(home).toContain('ZJU_CLASS_PERIODS')
    expect(courseCalendar).toContain('ZJU_CLASS_PERIODS')
  })

  it('keeps active routes in one namespace and redirects legacy teacher URLs', () => {
    const router = source('router/index.ts')

    expect(router).toContain("path: '/courses'")
    expect(router).toContain("path: '/course/:courseId/workspace/:mode(setup|build)?'")
    expect(router).toContain("path: '/course/:courseId/learn/:nodeId?'")
    expect(router).toContain("path: '/course/:courseId/ppt'")
    expect(router).toContain("component: () => import('../views/TeacherTeachingCalendarView.vue')")
    expect(router).toMatch(/path:\s*'\/teacher\/courses\/new'[\s\S]*?redirect:[\s\S]*?create:\s*'course'/)
    expect(router).toMatch(/path:\s*'\/teacher\/course\/:courseId\/files'[\s\S]*?redirect:[\s\S]*?name:\s*'course-workspace'/)
    expect(router).toMatch(/path:\s*'\/teacher\/course\/:courseId\/teaching-calendar'[\s\S]*?redirect:[\s\S]*?name:\s*'course-workspace'[\s\S]*?section:\s*'calendar'/)
    expect(router).toMatch(/path:\s*'\/teacher\/:pathMatch\(\.\*\)\*'[\s\S]*?redirect:\s*'\/courses'/)
    expect(router).not.toContain("import('../views/TeacherCourseOverviewView.vue')")
    expect(router).not.toContain("import('../views/TeacherCourseProductionView.vue')")
  })

  it('creates the course space from an always-expanded modal before opening the managed-asset workbench', () => {
    const create = source('views/TeacherCourseCreateView.vue')
    const store = source('stores/course.ts')

    expect(create).toContain('class="course-form"')
    expect(create).toContain('<dialog')
    expect(create).toContain("dialogRef.value?.showModal()")
    expect(create).toContain('<section class="course-details"')
    expect(create).not.toContain('<details')
    expect(create).not.toContain('<summary')
    expect(create).not.toContain('v-model="form.generateOutline"')
    expect(create).not.toContain('<CourseGenerationDialog')
    expect(create).not.toContain('type="file"')
    expect(create).not.toContain('localStorage')
    expect(create).toContain("courseStore.createTeacherCourseSpace")
    expect(create).toContain('generation_request:')
    expect(create).toContain('const learningGoal = form.teachingGoals.trim()')
    expect(create).not.toContain('form.teachingGoals || form.courseIntro || form.courseName')
    expect(create).toContain("requirements: ''")
    expect(create).not.toContain('additional_requirements: form.assessmentMethod')
    expect(create).not.toContain("composition_style: 'balanced'")
    expect(create).not.toContain("teaching_context: 'classroom'")
    expect(create).toContain("name: 'course-workspace'")
    expect(create).not.toContain("view: 'files'")
    expect(create).toContain("prepare: '1'")
    expect(create).not.toContain("generate: 'outline'")
    expect(create).not.toContain('section_count: Math.max')
    expect(create).not.toContain('class="workbench-preview"')
    expect(store).toContain('generation_request?: { subject: string } & CourseGenerationOptions')
  })

  it('edits the outline and lesson plan inline without a second lesson-plan drawer', () => {
    const workspace = source('views/CourseWorkspaceView.vue')
    const workbench = source('components/TeacherCourseWorkbench.vue')
    const lessonPlan = source('components/TeacherLessonPlanDocument.vue')

    expect(workspace).not.toContain('<GenerationLessonPlan')
    expect(workspace).not.toContain('lessonOpen')
    expect(workspace).toContain('v-model:outline-editing="outlineEditing"')
    expect(workspace).toContain('@open-outline="openOutlineEditor"')
    expect(workspace).not.toContain('v-model="outlineOpen"')
    expect(workbench).toContain('class="inline-outline-review"')
    expect(workbench).toContain("@confirmed=\"handleInlineOutlineConfirmed\"")
    expect(workspace).toContain('@generate-outline="startOutlineGeneration"')
    expect(workspace).not.toContain('<CourseGenerationDialog')
    expect(workspace).toContain("target_course_id: courseId.value")
    expect(workspace).toContain('@open-teaching-plan="openLessonPlan"')
    expect(workspace).toContain("requestedWorkbenchStage.value = 'lesson'")
    expect(workspace).toContain('requestedLessonId.value = lessonId')
    expect(workbench).toContain('<TeacherLessonPlanDocument')
    expect(workbench).not.toContain("emit('openTeachingPlan'")
    expect(lessonPlan).toContain('lessonStore.saveDraft')
    expect(lessonPlan).toContain('class="lesson-document"')
  })

  it('binds the file space to the stable course and presents one managed file tree', () => {
    const fileSpace = source('views/TeacherCourseSpaceView.vue')

    expect(fileSpace).toContain("params: embedded.value && props.courseId ? { course_id: props.courseId } : undefined")
    expect(fileSpace).toContain("course_id: props.courseId")
    expect(fileSpace).toContain("http.patch(`/api/teacher-course-spaces/${legacyMatches[0]!.package_id}`")
    expect(fileSpace).toContain('class="file-tree-pane"')
    expect(fileSpace).toContain('class="folder-navigation"')
    expect(fileSpace).toContain('<WorkspaceFolderTreeNode')
    expect(fileSpace).not.toContain('<el-tree')
    expect(fileSpace).toContain('class="file-list-pane"')
    expect(fileSpace).toContain('v-if="breadcrumbs.length" class="list-toolbar"')
    expect(fileSpace).not.toContain('class="toolbar-actions"')
    expect(fileSpace).toContain('class="file-inspector"')
    expect(fileSpace).toContain("t('courseFiles.columns.size')")
    expect(fileSpace).toContain('const inspectedNode = computed')
    expect(fileSpace).toContain("id: `content:${lesson.lesson_unit_id}`")
    expect(fileSpace).toContain("id: 'managed:teaching-calendar'")
    expect(fileSpace).toContain('async function exportManagedNode')
    expect(fileSpace).toContain("node.type === 'content'")
    expect(fileSpace).toContain("type CreateType = 'outline' | 'lesson_plan' | 'material' | 'ppt' | 'practice' | 'folder'")
    expect(fileSpace).not.toContain('class="new-button"')
    expect(fileSpace).not.toContain('<el-dropdown')
    expect(fileSpace).toContain('const canAddTeacherFiles = computed')
    expect(fileSpace).toContain("t('courseFiles.addMaterial')")
    expect(fileSpace).toContain(':data-role="assetRole(node)"')
    expect(fileSpace).toContain('function handleNodeClick(node: WorkspaceNode)')
    expect(fileSpace).toContain('function selectNode(node: WorkspaceNode)')
    expect(fileSpace).toContain("@dblclick=\"node.kind !== 'folder' && primaryAction(node)\"")
    expect(fileSpace).toContain('@click="handleNodeClick(node)"')
    expect(fileSpace).toContain("id: `ppt:${lesson.lesson_unit_id}`")
    expect(fileSpace).not.toContain('ppt || !uploadedPpts.length')
  })

  it('keeps teacher authoring assets out of the student page and routes practice through the question book', () => {
    const learning = source('views/LearningView.vue')
    const dock = source('components/LearningDock.vue')

    expect(learning).not.toContain('<CourseWorkspaceTabs')
    expect(learning).not.toContain('<CourseOutlineReview')
    expect(learning).not.toContain('<GenerationLessonPlan')
    expect(learning).not.toContain('<TeachingRepresentationsOverlay')
    expect(learning).not.toContain('<CourseProductionStage')
    expect(learning).not.toContain('<CourseGenerationGate')
    expect(learning).toContain('@question-book="openQuestionBook"')
    expect(learning).not.toContain("workspace === 'practice'")
    expect(dock).toContain('data-domain="question-book"')
  })

  it('does not repeat controls with explanatory copy on the active teacher path', () => {
    const home = source('views/TeacherTeachingCalendarView.vue')
    const courseDialog = source('components/CreateCourseSpaceDialog.vue')
    const fileSpace = source('views/TeacherCourseSpaceView.vue')
    const generationDialog = source('components/CourseGenerationDialog.vue')
    const taskCenter = source('components/CourseTaskCenter.vue')
    const questionBank = source('components/QuestionBankReviewPanel.vue')

    expect(home).not.toContain("t('teacherHome.noSearchResultsHelp')")
    expect(courseDialog).not.toContain("t('courseSpaceCreate.rule')")
    expect(fileSpace).not.toContain('<p class="asset-create-help"')
    expect(fileSpace).not.toContain('emptyFolderHelp')
    expect(fileSpace).not.toContain('sourceHint')
    expect(fileSpace).not.toContain('<p v-if="createType === \'ppt\'" class="ppt-origin-note"')
    expect(fileSpace).not.toContain("t('courseFiles.workbench.stepLabel')")
    expect(fileSpace).not.toContain('category-console__step')
    expect(generationDialog).not.toContain('<p class="starting-point-note"')
    expect(generationDialog).not.toContain('<p class="difficulty-summary"')
    expect(taskCenter).not.toContain('currentReviewHelp')
    expect(taskCenter).not.toContain('guided-workflow')
    expect(taskCenter).not.toContain('<strong>{{ t(\'courseTasks.title\'')
    expect(questionBank).not.toContain("t('questionBank.noMatchingQuestionsHelp'")
  })
})
