use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - bing
      - baidu
      - brave
      - startpage
      - qwant
      - yahoo
      - sogou
      - quark
      - wikipedia
      - arxiv
      - pubmed
      - openalex
      - crossref
      - bing images
      - baidu images
      - quark images
      - sogou images
      - wikicommons.images

general:
  debug: false
  instance_name: "Lingzhi Retrieval"

search:
  safe_search: 2
  autocomplete: ""
  formats:
      - json

server:
  secret_key: "overridden-by-SEARXNG_SECRET"
  limiter: false
  public_instance: false
  image_proxy: false
  method: "POST"

outgoing:
  request_timeout: 3.0
  max_request_timeout: 12.0

ui:
  query_in_title: false

engines:
  - name: bing
    disabled: false
  - name: baidu
    disabled: false
  - name: brave
    disabled: false
  - name: startpage
    disabled: false
  - name: qwant
    disabled: false
  - name: yahoo
    disabled: false
  - name: sogou
    disabled: false
  - name: quark
    disabled: false
  - name: wikipedia
    display_type: ["infobox", "list"]
  - name: openalex
    disabled: false
  - name: crossref
    disabled: false
  - name: bing images
    base_url: https://cn.bing.com
    disabled: false
  - name: baidu images
    disabled: false
  - name: quark images
    disabled: false
  - name: sogou images
    disabled: false
  - name: wikicommons.images
    engine: wikicommons
    shortcut: wci
    categories: images
    wc_search_type: image
    timeout: 10.0
    disabled: false
